# Generated by Django 3.2.12 on 2022-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220721_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_frontend',
            name='l1n',
            field=models.DecimalField(db_column='L1N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='l1s',
            field=models.DecimalField(db_column='L1S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='speed',
            field=models.DecimalField(db_column='Speed', decimal_places=2, default='', editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v1n',
            field=models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v1s',
            field=models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v3n',
            field=models.DecimalField(db_column='V3N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v3n_prot',
            field=models.DecimalField(db_column='V3N Prot', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v3s',
            field=models.DecimalField(db_column='V3S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='l1n',
            field=models.DecimalField(db_column='L1N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='l1s',
            field=models.DecimalField(db_column='L1S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v1n',
            field=models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v1s',
            field=models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v3n',
            field=models.DecimalField(db_column='V3N_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v3n_prot',
            field=models.DecimalField(db_column='V3N Prot', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v3s',
            field=models.DecimalField(db_column='V3S_pks', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='metratr116',
            name='speed',
            field=models.DecimalField(db_column='Speed', decimal_places=2, max_digits=4),
        ),
    ]
