# Generated by Django 3.2.12 on 2023-01-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cta_backup',
            fields=[
                ('id', models.IntegerField(db_column='Unique_ID', primary_key=True, serialize=False)),
                ('car_num', models.FloatField(db_column='Car_num')),
                ('run_num', models.FloatField(db_column='Run_num')),
                ('axle', models.FloatField(db_column='Axle')),
                ('train_id', models.CharField(db_column='TrainDateTime', default='', max_length=255)),
                ('speed', models.DecimalField(db_column='Speed', decimal_places=2, max_digits=25)),
                ('l2w', models.DecimalField(db_column='L2W_pks', decimal_places=2, max_digits=4)),
                ('l2e', models.DecimalField(db_column='L2E_pks', decimal_places=2, max_digits=4)),
                ('l1w', models.DecimalField(db_column='L1W_pks', decimal_places=2, max_digits=4)),
                ('l1e', models.DecimalField(db_column='L1E_pks', decimal_places=2, max_digits=4)),
                ('v2w', models.DecimalField(db_column='V2W_pks', decimal_places=2, max_digits=4)),
                ('v2e', models.DecimalField(db_column='V2E_pks', decimal_places=2, max_digits=4)),
                ('v1w', models.DecimalField(db_column='V1W_pks', decimal_places=2, max_digits=4)),
                ('v1e', models.DecimalField(db_column='V1E_pks', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'cta_backup_10222022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Backup_Frontend',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_id', models.CharField(db_column='TrainDateTime', default='', max_length=255)),
                ('v1n', models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=4)),
                ('v1s', models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=4)),
                ('l1n', models.DecimalField(db_column='L1N_pks', decimal_places=2, max_digits=4)),
                ('l1s', models.DecimalField(db_column='L1S_pks', decimal_places=2, max_digits=4)),
                ('v3n', models.DecimalField(db_column='V3N_pks', decimal_places=2, max_digits=4)),
                ('v3s', models.DecimalField(db_column='V3S_pks', decimal_places=2, max_digits=4)),
                ('v3n_prot', models.DecimalField(db_column='V3NProt', decimal_places=2, max_digits=4)),
                ('carloc', models.CharField(db_column='carOrLoc', max_length=255)),
                ('speed', models.DecimalField(db_column='Speed', decimal_places=2, default='', editable=False, max_digits=4)),
            ],
            options={
                'db_table': 'metra_backup_frontend_0918',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Backup_Speed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_id', models.CharField(db_column='TrainDateTime', default='', max_length=255)),
                ('v1n', models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=4)),
                ('v1s', models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=4)),
                ('l1n', models.DecimalField(db_column='L1N_pks', decimal_places=2, max_digits=4)),
                ('l1s', models.DecimalField(db_column='L1S_pks', decimal_places=2, max_digits=4)),
                ('v3n', models.DecimalField(db_column='V3N_pks', decimal_places=2, max_digits=4)),
                ('v3s', models.DecimalField(db_column='V3S_pks', decimal_places=2, max_digits=4)),
                ('v3n_prot', models.DecimalField(db_column='V3N Prot', decimal_places=2, max_digits=4)),
                ('carloc', models.CharField(db_column='carOrLoc', max_length=255)),
                ('speed', models.DecimalField(db_column='Speed', decimal_places=2, max_digits=25)),
            ],
            options={
                'db_table': 'final_dataset_speed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Metratr116',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_id', models.CharField(db_column='TrainDateTime', max_length=255)),
                ('v1n', models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=4)),
                ('v1s', models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=4)),
                ('l1n', models.DecimalField(db_column='L1N_pks', decimal_places=2, max_digits=4)),
                ('l1s', models.DecimalField(db_column='L1S_pks', decimal_places=2, max_digits=4)),
                ('v3n', models.DecimalField(db_column='V3N_pks', decimal_places=2, max_digits=4)),
                ('v3s', models.DecimalField(db_column='V3S_pks', decimal_places=2, max_digits=4)),
                ('v3n_prot', models.DecimalField(db_column='V3N Prot', decimal_places=2, max_digits=4)),
                ('carloc', models.CharField(db_column='carOrLoc', max_length=255)),
                ('speed', models.DecimalField(db_column='Speed', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'metratr116',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Metratr116_reprocessed',
            fields=[
                ('tr_id', models.CharField(db_column='TrainID', max_length=255, primary_key=True, serialize=False)),
                ('tr_date', models.CharField(db_column='TrainDateTime', max_length=255)),
                ('v1n', models.DecimalField(db_column='V1N_pks', decimal_places=2, max_digits=5)),
                ('v1s', models.DecimalField(db_column='V1S_pks', decimal_places=2, max_digits=5)),
                ('v2s', models.DecimalField(db_column='V2S_pks', decimal_places=2, max_digits=5)),
                ('axle_num', models.DecimalField(db_column='AxleNumber', decimal_places=2, max_digits=4)),
                ('v3s_prot', models.DecimalField(db_column='V3S_Prot_pks', decimal_places=2, max_digits=4)),
                ('carloc', models.CharField(db_column='carOrLoc', max_length=255)),
                ('speed', models.DecimalField(db_column='Speed', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'METRA_REPROCESSED',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.djangocontenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.djangocontenttype'),
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.authpermission')),
            ],
        ),
    ]
