# Generated by Django 3.2.12 on 2022-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup_frontend',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='metratr116',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='backup_frontend',
            name='date',
        ),
        migrations.AddField(
            model_name='backup_frontend',
            name='tr_id',
            field=models.CharField(db_column='TrainDateTime', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='backup_frontend',
            name='v3n_prot',
            field=models.DecimalField(db_column='V3N Prot', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='carloc',
            field=models.CharField(db_column='carOrLoc', default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='l1n',
            field=models.DecimalField(db_column='L1N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='l1s',
            field=models.DecimalField(db_column='L1S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='speed',
            field=models.DecimalField(db_column='Speed', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v1n',
            field=models.DecimalField(db_column='V1N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v1s',
            field=models.DecimalField(db_column='V1S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v3n',
            field=models.DecimalField(db_column='V3N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_frontend',
            name='v3s',
            field=models.DecimalField(db_column='V3S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='metratr116',
            name='speed',
            field=models.DecimalField(db_column='Speed', decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='metratr116',
            name='tr_id',
            field=models.CharField(db_column='TrainDateTime', max_length=255),
        ),
        migrations.AlterModelTable(
            name='backup_frontend',
            table='final_dataset',
        ),
        migrations.AlterModelTable(
            name='metratr116',
            table='metratr116',
        ),
    ]
