# Generated by Django 3.2.12 on 2022-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220719_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup_speed',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='backup_speed',
            name='date',
        ),
        migrations.AddField(
            model_name='backup_speed',
            name='tr_id',
            field=models.CharField(db_column='TrainDateTime', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='backup_speed',
            name='v3n_prot',
            field=models.DecimalField(db_column='V3N Prot', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='carloc',
            field=models.CharField(db_column='carOrLoc', default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='l1n',
            field=models.DecimalField(db_column='L1N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='l1s',
            field=models.DecimalField(db_column='L1S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='speed',
            field=models.DecimalField(db_column='Speed', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v1n',
            field=models.DecimalField(db_column='V1N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v1s',
            field=models.DecimalField(db_column='V1S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v3n',
            field=models.DecimalField(db_column='V3N_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterField(
            model_name='backup_speed',
            name='v3s',
            field=models.DecimalField(db_column='V3S_pks', decimal_places=2, default='', editable=False, max_digits=25),
        ),
        migrations.AlterModelTable(
            name='backup_speed',
            table='final_dataset_speed',
        ),
    ]
